package main;
/**
* Nadeem Abdul Hamid, 2025.
*/

import java.util.Objects;

/** 
 * Represents a (potentially uninitialized) range of values with 
 * a min and a max.
 */
public class Range {
    boolean initialized;
    int min;
    int max;
    
    public Range() {
        initialized = false;
    }

    public Range(int val) {
        initialized = true;
        min = val;
        max = val;
    }

    public Range(int min, int max) {
        initialized = true;
        this.min = min;
        this.max = max;
    }

    /**
     * Adds a value to this range, updating the min and max as needed.
     */
    public void addValue(int value) {
		if (!this.initialized) {
			initialized = true;
			this.min = this.max = value;
		} else {
			this.min = Math.min(value,  this.min);
			this.max = Math.max(value, this.max);
		}
    }

    /**
     * Returns a string of a JSON object representing this range,
     * or "false" if this range is not initialized.
     */
	public String toJSONString() {
		if (!this.initialized) {
			return "false";
		} else {
			return "{ \"min\": " + this.min + ", \"max\": " + this.max + " }";
		}
	}

    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(initialized, min, max);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof Range))
            return false;
        Range other = (Range) obj;
        return initialized == other.initialized && min == other.min && max == other.max;
    }

    @Override
    public String toString() {
        return "Range [initialized=" + initialized + ", min=" + min + ", max=" + max + "]";
    }
        
}
