package main;
/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;
import java.util.function.Predicate;

import org.json.JSONArray;

import funcobjs.*;
import list.*;
import media.*;

/**
 * Represents our online media store, which keeps track of a few books
 * available for sale.
 */
public class Store {
	ILoM items;		// catalog of items available in this store
	ILo<Integer> cart;		// list of item ids that are currently in the cart
	String coupon;	// coupon code for a discount applied to the cart, "" if none is applied, always in uppercase
	
	public Store(ILoM items, ILo<Integer> cart, String coupon) {
		this.items = items;
		this.cart = cart;
		this.coupon = coupon;
	}

	public Store(ILoM items) {
		this(items, new MTLo<Integer>(), "");
	}

	/**
	 * Returns a string representation of a JSON array of the ids of all items
	 * in this store.
	 */
	public String catalog() {
		return "[" + this.items.collectIds() + "]";
	}

	/**
	 * Returns a string representation of a JSON array of the ids of all items
	 * in this store that satisfy the given predicate.
	 */
	public String catalog(Predicate<IMedia> pred) {
		return "[" + this.items.filter(pred).collectIds() + "]";
	}


	
	/**
	 * Returns a string representation of the JSON object for the item 
	 * with the given id.
	 */
	public String itemInfoAsJSON(int id) {
		IMedia item = this.items.findItem(id);
		if (item == null) {
			return "";
		} else {
			return item.toJSONString();
		}
	}
	
	/**
	 * Produces a string representation of a JSON array of the tags of all items
	 */
	public String tagsList(int limit) {
		if (limit < 0) {
			return items.collectTags().asJSONList().toString();
		} else {
			return items.collectTags().take(limit).asJSONList().toString();
		}
	}

	/**
	 * Produces a JSON array of pairs (JSON array of a string and a number)
	 * representing the count of each tag in the store for all tags of all
	 * items.
	 */
	public String tagCounts() {
		ILo<String> alltags = items.collectTags();
		return tagTally(alltags).toString();
	}

	private JSONArray tagTally(ILo<String> tags) {
		if (tags.isEmpty()) {
			return new JSONArray();
		} else {
			String tag = tags.getFirst();
			int count = tags.count(tag);
			return new JSONArray().put(new JSONArray().put(tag).put(count)).putAll(tagTally(tags.removeAll(tag)));
		}
	}
	
	/**
	 * Returns (JSON string) the number of items in the cart.
	 */
	public String cartSize() {
		return Integer.toString(cart.size());
	}

	/**
	 * Returns a JSON array of the ids of all items in the cart.
	 */
	public String cartList() {
		return this.cart.asJSONList().toString();
	}

	/**
	 * Adds the given id to the cart.
	 * Produces "true" if successful, "false" if the item was
	 * already in the cart.
	 */
	public String addToCart(int id) {
		if (this.cart.contains(id)) {
			return "false";
		} else {
			this.cart = new ConsLo<Integer>(id, this.cart);
			return "true";
		}
	}

	/**
	 * Removes the given id from the cart.
	 * Returns "true" if the id was found otherwise
	 * "false" if the id is not in the cart.
	 */
	public String removeFromCart(int id) {
		if (!this.cart.contains(id)) {
			return "false";
		} else {
			this.cart = this.cart.removeAll(id);
			return "true";
		}
	}

	/**
	 * Returns the currently applied coupon as a JSON quoted string, "\"\""" if none.
	 */
	public String getCoupon() {
		return StringHelpers.quote(this.coupon);
	}

	/**
	 * Applies the given coupon to the cart, as long as there isn't already
	 * a coupon applied. Coupon codes should be turned into all uppercase letters
	 * when they are applied.
	 * Returns "true" if successful, "false" if there was already a coupon applied.
	 */
	public String applyCoupon(String code) {
		if (this.coupon.equals("")) {
			this.coupon = code.toUpperCase();
			return "true";
		} else {
			return "false";
		}
	}
	
	/**
	 * Removes the currently applied coupon from the cart.
	 * Returns "false" if there was no coupon applied, "true" otherwise.
	 */
	public String removeCoupon(String code) {
		if (this.coupon.equals(code.toUpperCase())) {
			this.coupon = "";
			return "true";
		} else {
			return "false";
		}
	}

	/**
	 * Returns a JSON string representation of the range of 
	 * years of all items in the store.
	 */
	public String yearRangeAsJSON() {
		return rangeAsJSON(new YearExtractor());
	}

	/**
	 * Returns a JSON string representation of the range of 
	 * years of all items in the store.
	 */
	public String priceRangeAsJSON() {
		return rangeAsJSON(new PriceExtractor());
	}

	/**
	 * Returns a JSON string representation of the range of 
	 * items in this store based on the extraction function.
	 */
	public String rangeAsJSON(IIntExtractor obj) {
		return this.items.range(obj).toJSONString();
	}


	// AUTOGENERATED CODE BELOW

	@Override
	public int hashCode() {
		return Objects.hash(items, cart, coupon);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!(obj instanceof Store))
			return false;
		Store other = (Store) obj;
		return Objects.equals(items, other.items) && Objects.equals(cart, other.cart)
				&& Objects.equals(coupon, other.coupon);
	}

	@Override
	public String toString() {
		return "Store [items=" + items + ", cart=" + cart + ", coupon=" + coupon + "]";
	}
	
}
