/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;

/**
 * Represents a non-empty list of media.
 */
public class ConsLoM implements ILoM {
    IMedia first;
    ILoM rest;

    public ConsLoM(IMedia first, ILoM rest) {
        this.first = first;
        this.rest = rest;
    }
    
    /**
     * Produces a comma-separated string of all the
     * ids of the media in this list.
     */
    public String collectIds() {
        String restStr = this.rest.collectIds();
        if (restStr.equals("")) {
            return this.first.getId() + "";
        } else {
            return this.first.getId() + ", " + restStr;
        }
    }

    /**
	 * Returns a string representation of the JSON object for the item 
	 * with the given id in this list. If the item is not found, returns "".
     */
	public String infoAsJSON(int id) {
        if (this.first.getId() == id) {
            return this.first.toJSONString();
        } else {
            return this.rest.infoAsJSON(id);
        }
    }

    /**
     * Return a list of all tags of all items in this list
     */
    public ILoS collectTags() {
        return this.first.getTags().append(this.rest.collectTags());
    }


    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLoM))
            return false;
        ConsLoM other = (ConsLoM) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLoM [first=" + first + ", rest=" + rest + "]";
    }

}
