/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;
import org.json.JSONArray;

/** 
 * Represents a non-empty list of strings.
 */
public class ConsLoS implements ILoS {
    String first;
    ILoS rest;

    public ConsLoS(String first, ILoS rest) {
        this.first = first;
        this.rest = rest;
    }

	/** Produce a representation of this list as a JSON array */
	public JSONArray asJSONList() {
        return new JSONArray().put(this.first).putAll(this.rest.asJSONList());
	}

    /**
     * Produce a new list that is this list append to all the
     * items in that.
     */
    public ILoS append(ILoS that) {
		return new ConsLoS(this.first, this.rest.append(that));
	}

	/**
     * Produce a new list with only the first n items of this list.
     */
    public ILoS take(int n) {
		if (n == 0) {
            return new MTLoS();
        } else {
            return new ConsLoS(this.first, this.rest.take(n - 1));
        }
	}
    
    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLoS))
            return false;
        ConsLoS other = (ConsLoS) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLoS [first=" + first + ", rest=" + rest + "]";
    }

}
