/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;

/** 
 * Represents a non-empty list of strings.
 */
public class ConsLoS implements ILoS {
    String first;
    ILoS rest;

    public ConsLoS(String first, ILoS rest) {
        this.first = first;
        this.rest = rest;
    }

	/** Produce a string representation of this list as a JSON array */
	public String asJSONList() {
		return "[" + this.join(",", true) + "]";
	}

    /** Produce a single string with all the strings in this list quoted 
     * and joined by the given separator. */
    public String join(String sep, boolean quote) {
        String restJoin = this.rest.join(sep, quote); 
		if (restJoin.equals("")) {
            if (quote) {
                return StringHelpers.quote(this.first);
            } else {
                return this.first;
            }
		} else {
            if (quote) {
                return StringHelpers.quote(this.first) + sep + restJoin;
            } else {
                return this.first + sep + restJoin;
            }
		}
    }

    
    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLoS))
            return false;
        ConsLoS other = (ConsLoS) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLoS [first=" + first + ", rest=" + rest + "]";
    }

}
