import java.util.Objects;

/**
 * Nadeem Abdul Hamid, 2025.
 */

public class ConsLo<T> implements ILo<T> {
    T first;
    ILo<T> rest;

    public ConsLo(T first, ILo<T> rest) {
        this.first = first;
        this.rest = rest;
    }

	/** Produce the number of elements in this list */
	@Override
	public int size() {
		return 1 + this.rest.size();
	}


    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @SuppressWarnings("rawtypes")
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLo))
            return false;
        ConsLo other = (ConsLo) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLo [first=" + first + ", rest=" + rest + "]";
    }

}
