import java.util.Objects;

import org.json.JSONArray;

/**
 * Nadeem Abdul Hamid, 2025.
 */

public class ConsLo<T> implements ILo<T> {
    T first;
    ILo<T> rest;

    public ConsLo(T first, ILo<T> rest) {
        this.first = first;
        this.rest = rest;
    }

	/** Produce the number of elements in this list */
	@Override
	public int size() {
		return 1 + this.rest.size();
	}

	/** Produce a representation of this list as a JSON array */
	public JSONArray asJSONList() {
        return new JSONArray().put(this.first).putAll(this.rest.asJSONList());
	}

    /** Determine if this list contains the given number */
    @Override
    public boolean contains(T elt) {
        return this.first.equals(elt) || this.rest.contains(elt);
    }

    /** Produce a copy of this list with the given number removed */
    @Override
    public ILo<T> removeAll(T elt) {
        if (this.first.equals(elt)) {
            return this.rest.removeAll(elt);
        } else {
            return new ConsLo<T>(this.first, this.rest.removeAll(elt));
        }
    }

    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @SuppressWarnings("rawtypes")
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLo))
            return false;
        ConsLo other = (ConsLo) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLo [first=" + first + ", rest=" + rest + "]";
    }

}
