import java.util.Objects;

public class ConsLoN implements ILoN {
    int first;
    ILoN rest;

    public ConsLoN(int first, ILoN rest) {
        this.first = first;
        this.rest = rest;
    }

    /** @inheritDoc */
    @Override
    public int size() {
        return 1 + this.rest.size();
    }

    /** @inheritDoc */
    @Override
    public boolean contains(int n) {
        return this.first == n || this.rest.contains(n);
    }

    /**
     * @inheritDoc
     * Note: Removes all copies of n from the list.
     */
    @Override
    public ILoN remove(int n) {
        if (this.first == n) {
            return this.rest.remove(n);
        } else {
            return new ConsLoN(this.first, this.rest.remove(n));
        }
    }

    /** @inheritDoc */
    @Override
    public String asJSONList() {
        return "[" + this.join(",") + "]";
    }

    /** @inheritDoc */
    @Override
    public String join(String sep) {
        String restJoin = this.rest.join(sep); 
		if (restJoin.equals("")) {
            return Integer.toString(this.first);
		} else {
            return this.first + sep + restJoin;
		}
    }

    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLoN))
            return false;
        ConsLoN other = (ConsLoN) obj;
        return first == other.first && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLoN [first=" + first + ", rest=" + rest + "]";
    }

}
