/**
 * Nadeem Abdul Hamid, 2025.
 */

/** 
 * Represents an empty list of media.
 */
public class MTLoM implements ILoM {

    /** 
     * Produces a comma-separated string of all the
     * ids of the media in this list.
     */
    public String collectIds() {
        return "";
    }

    /**
	 * Returns a string representation of the JSON object for the item 
	 * with the given id in this list. If the item is not found, returns "".
     */
	public String infoAsJSON(int id) {
        return "";
    }

    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLoM;
	}

	@Override
	public int hashCode() {
		return MTLoM.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLoM []";
    }
}
