public class MTLoS implements ILoS {
    

	/** Produce a string representation of this list as a JSON array */
	public String asJSONList() {
		return "[]";
	}

    /** Produce a single string with all the strings in this list quoted 
     * and joined by the given separator. */
    public String join(String sep, boolean quote) {
		return "";
	}

	/**
     * Produce a new list that is this list append to all the
     * items in that.
     */
    public ILoS append(ILoS that) {
		return that;
	}

	/**
     * Produce a new list with only the first n items of this list.
     */
    public ILoS take(int n) {
		return this;
	}

    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLoS;
	}

	@Override
	public int hashCode() {
		return MTLoS.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLoS []";
    }
}
