import org.json.JSONArray;

public class MTLoN implements ILoN {
    
    /** @inheritDoc */
    @Override
    public int size() {
        return 0;
    }

    /** @inheritDoc */
    @Override
    public boolean contains(int n) {
        return false;
    }

    /** @inheritDoc */
    @Override
    public ILoN remove(int n) {
        return this;
    }

    /** @inheritDoc */
    @Override
    public JSONArray asJSONList() {
        return new JSONArray();
    }

    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLoN;
	}

	@Override
	public int hashCode() {
		return MTLoN.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLoN []";
    }


}
