/**
 * Nadeem Abdul Hamid, 2025.
 */

public class MTLo<T> implements ILo<T> {
    
	/** Produce the number of elements in this list */
	@Override
	public int size() {
		return 0;
	}


    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLo;
	}

	@Override
	public int hashCode() {
		return MTLo.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLo []";
    }

}
