/**
 * Nadeem Abdul Hamid, 2025.
 */

/** 
 * Represents an empty list of media.
 */
public class MTLoM implements ILoM {

    /** 
     * Produces a comma-separated string of all the
     * ids of the media in this list.
     */
    public String collectIds() {
        return "";
    }

    /**
	 * Returns the media item with the given id in this list.
     * Produces null if not found.
     */
	public IMedia findItem(int id) {
        return null;
    }

    /**
     * Return a list of all tags of all items in this list
     */
    public ILo<String> collectTags() {
        return new MTLo<>();
    }

    /**
     * Return the range of years associated with all items in this list
     */
    public Range yearRange() {
        return new Range();
    }

    /**
     * Return the range of prices of all items in this list
     */
    public Range priceRange() {
        return new Range();
    }

    /**
     * 
     */
    @Override
    public Range range(IIntExtractor obj) {
        return new Range();
    }


    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLoM;
	}

	@Override
	public int hashCode() {
		return MTLoM.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLoM []";
    }
}
