import org.json.JSONArray;

/**
 * Nadeem Abdul Hamid, 2025.
 */

public class MTLo<T> implements ILo<T> {
    
	/** Produce the number of elements in this list */
	@Override
	public int size() {
		return 0;
	}

    /** Produce a string representation of this list as a JSON array */
	@Override
    public JSONArray asJSONList() {
        return new JSONArray();
    }

    /** Determine if this list contains the given number */
    @Override
    public boolean contains(T elt) {
        return false;
    }

    /** Produce a copy of this list with the given number removed */
    @Override
    public ILo<T> removeAll(T elt) {
        return this;
    }

    /**
     * Produce a new list that is this list append to all the
     * items in that.
     */
    @Override
    public ILo<T> append(ILo<T> that) {
		return that;
	}

	/**
     * Produce a new list with only the first n items of this list.
     */
    @Override
    public ILo<T> take(int n) {
		return this;
	}

    // AUTOGENERATED CODE BELOW

	@Override
	public boolean equals(Object other) {
		return other instanceof MTLo;
	}

	@Override
	public int hashCode() {
		return MTLo.class.hashCode();
	}

    @Override
    public String toString() {
        return "MTLo []";
    }

}
