/**
 * Nadeem Abdul Hamid, 2025.
 */

 import java.util.Objects;

 /** 
  * Represents rating information for an item in our media store.
  */
 public class Rating {
	double average;
	int count;
    
    public Rating(double average, int count) {
        this.average = average;
        this.count = count;
    }

    /**
     * Produces a string representation of the average rating, with
     * shortened forms for thousands and millions.
     */
    private String formatCount() {
		if (count < 1000) {
			return "" + count;
		} else if (count < 1000000) {
			return Math.round(count/1000.0) + "K";
		} else {
			return Math.round(count/1000000.0) + "M";
		}
	}

    /**
     * Return a JSON fields representing this rating, as a fragment
     * of a larger JSON object.
     */
    public String toJSONStringFragment() {
        return String.format("\"rating-average\": %.1f, \"rating-count\": \"%s\"", this.average, formatCount());
    }


    // AUTOGENERATED CODE BELOW

    /**
     * Return a string representation of this rating.
     */
    public String toString() {
        return String.format("%.2f (%d ratings)", this.average, this.count);
    }

    /**
     * Return true if this rating is equal to the given rating.
     */
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj == null || obj.getClass() != this.getClass()) {
            return false;
        }
        Rating other = (Rating) obj;
        return this.average == other.average && this.count == other.count;
    }

    /**
     * Return a hash code for this rating.
     */
    public int hashCode() {
        return Objects.hash(this.average, this.count);
    }
}
