/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;

/**
 * Represents our online media store, which keeps track of a few books
 * available for sale.
 */
public class Store {
	ILoM items;		// catalog of items available in this store
	ILoN cart;		// list of item ids that are currently in the cart
	
	public Store(ILoM items, ILoN cart) {
		this.items = items;
		this.cart = cart;
	}

	public Store(ILoM items) {
		this(items, new MTLoN());
	}

	/**
	 * Returns a string representation of a JSON array of the ids of all items
	 * in this store.
	 */
	public String catalog() {
		return "[" + this.items.collectIds() + "]";
	}
	
	/**
	 * Returns a string representation of the JSON object for the item 
	 * with the given id.
	 */
	public String itemInfoAsJSON(int id) {
		IMedia item = this.items.findItem(id);
		if (item == null) {
			return "";
		} else {
			return item.toJSONString();
		}
	}
	
	/**
	 * Produces a string representation of a JSON array of the tags of all items
	 */
	public String tagsList(int limit) {
		if (limit < 0) {
			return items.collectTags().asJSONList();
		} else {
			return items.collectTags().take(limit).asJSONList();
		}
	}

	// stub!
	public String tagCounts() {
		return "[ [\"fiction\", 1], [\"nonfiction\", 1], [\"textbook\", 1] ]";
	}
	
	/**
	 * Returns (JSON string) the number of items in the cart.
	 */
	public String cartSize() {
		return Integer.toString(cart.size());
	}

	/**
	 * Returns a JSON array of the ids of all items in the cart.
	 */
	public String cartList() {
		return this.cart.asJSONList();
	}

	/**
	 * Adds the given id to the cart.
	 * Produces "true" if successful, "false" if the item was
	 * already in the cart.
	 */
	public String addToCart(int id) {
		if (this.cart.contains(id)) {
			return "false";
		} else {
			this.cart = new ConsLoN(id, this.cart);
			return "true";
		}
	}

	/**
	 * Removes the given id from the cart.
	 * Returns "true" if the id was found otherwise
	 * "false" if the id is not in the cart.
	 */
	public String removeFromCart(int id) {
		if (!this.cart.contains(id)) {
			return "false";
		} else {
			this.cart = this.cart.remove(id);
			return "true";
		}
	}

	// AUTOGENERATED CODE BELOW

	@Override
	public int hashCode() {
		return Objects.hash(items, cart);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!(obj instanceof Store))
			return false;
		Store other = (Store) obj;
		return Objects.equals(items, other.items) && Objects.equals(cart, other.cart);
	}

	@Override
	public String toString() {
		return "Store [items=" + items + ", cart=" + cart + "]";
	}


	
}
