package list;
/**
 * Nadeem Abdul Hamid, 2025.
 */

import java.util.Objects;
import java.util.function.Predicate;

import funcobjs.IIntExtractor;
import main.Range;
import media.IMedia;

/**
 * Represents a non-empty list of media.
 */
public class ConsLoM implements ILoM {
    IMedia first;
    ILoM rest;

    public ConsLoM(IMedia first, ILoM rest) {
        this.first = first;
        this.rest = rest;
    }
    
    /**
     * Produces a comma-separated string of all the
     * ids of the media in this list.
     */
    public String collectIds() {
        String restStr = this.rest.collectIds();
        if (restStr.equals("")) {
            return this.first.getId() + "";
        } else {
            return this.first.getId() + ", " + restStr;
        }
    }

    /**
	 * Returns the media item with the given id in this list.
     * Produces null if not found.
     */
	public IMedia findItem(int id) {
        if (this.first.getId() == id) {
            return this.first;
        } else {
            return this.rest.findItem(id);
        }
    }

    /**
     * Return a list of all tags of all items in this list
     */
    public ILo<String> collectTags() {
        return this.first.getTags().append(this.rest.collectTags());
    }

    /**
     * Return the range of years associated with all items in this list
     */
    public Range yearRange() {
        Range r = this.rest.yearRange();
        r.addValue(this.first.getYear());
        return r;
    }

    /**
     * Return the range of prices of all items in this list
     */
    public Range priceRange() {
        Range r = this.rest.priceRange();
        r.addValue(this.first.salePrice());
        return r;
    }

    /**
     * 
     */
    @Override
    public Range range(IIntExtractor obj) {      
        Range r = this.rest.range(obj);
        int value = obj.extract(this.first);
        r.addValue(value);
        return r;
    }

    /**
     * Produce a list of only the "print" media from this list
     */
    public ILoM onlyPrint() {
        if (this.first.typeMatches("print")) {
            return new ConsLoM(this.first, this.rest.onlyPrint());
        } else {
            return this.rest.onlyPrint();
        }
    }

    /**
     * Produce a list of only media published/produced after 
     * 2000 from this list
     */
	public ILoM after2000() {
        if (this.first.getYear() > 2000) {
            return new ConsLoM(this.first, this.rest.after2000());
        } else {
            return this.rest.after2000();
        }
    }

    /**
     * Produce a list of only media from this list that satisfy the given predicate
     */
    public ILoM filter(Predicate<IMedia> pred) {
        if (pred.test(this.first)) {
            return new ConsLoM(this.first, this.rest.filter(pred));
        } else {
            return this.rest.filter(pred);
        }

    }


    // AUTOGENERATED CODE BELOW

    @Override
    public int hashCode() {
        return Objects.hash(first, rest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof ConsLoM))
            return false;
        ConsLoM other = (ConsLoM) obj;
        return Objects.equals(first, other.first) && Objects.equals(rest, other.rest);
    }

    @Override
    public String toString() {
        return "ConsLoM [first=" + first + ", rest=" + rest + "]";
    }

}
