package media;
/**
 * Nadeem Abdul Hamid, 2025.
 */

 import java.util.Objects;

import org.json.JSONArray;
import org.json.JSONObject;

 /** 
  * Represents rating information for an item in our media store.
  */
 public class Rating {
	double average;
	int count;
    
    public Rating(double average, int count) {
        this.average = average;
        this.count = count;
    }

    /**
     * Return the average rating of this item.
     */
    public double getAverage() {
        return this.average;
    }

    /**
     * Produces a string representation of the average rating, with
     * shortened forms for thousands and millions.
     */
    private String formatCount() {
		if (count < 1000) {
			return "" + count;
		} else if (count < 1000000) {
			return Math.round(count/1000.0) + "K";
		} else {
			return Math.round(count/1000000.0) + "M";
		}
	}

    /** 
     * Produces a JSON array of star icons to represent the average rating.
     * Use the string "fa-regular fa-star" for empty stars, "fa-solid fa-star" for full stars,
     * and "fa-regular fa-star-half-stroke" for partial (half) stars.
     */
    private JSONArray starIcons() {
		String star1 = average < 0.3 ? "fa-regular fa-star" : average  < 0.9 ? "fa-regular fa-star-half-stroke" :  "fa-solid fa-star";
		String star2 = average < 1.3 ? "fa-regular fa-star" : average  < 1.9 ? "fa-regular fa-star-half-stroke" :  "fa-solid fa-star";
		String star3 = average < 2.3 ? "fa-regular fa-star" : average  < 2.9 ? "fa-regular fa-star-half-stroke" :  "fa-solid fa-star";
		String star4 = average < 3.3 ? "fa-regular fa-star" : average  < 3.9 ? "fa-regular fa-star-half-stroke" :  "fa-solid fa-star";
		String star5 = average < 4.3 ? "fa-regular fa-star" : average  < 4.9 ? "fa-regular fa-star-half-stroke" :  "fa-solid fa-star";
		
		return new JSONArray()
				.put(star1).put(star2).put(star3).put(star4).put(star5);
    }

    /**
     * 
     */
    public JSONObject addToJSONObject(JSONObject obj) {
        return obj.put("rating-average", this.average).put("rating-count", this.formatCount())
                .put("star-icons", this.starIcons());
    }


    // AUTOGENERATED CODE BELOW

    /**
     * Return a string representation of this rating.
     */
    public String toString() {
        return String.format("%.2f (%d ratings)", this.average, this.count);
    }

    /**
     * Return true if this rating is equal to the given rating.
     */
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj == null || obj.getClass() != this.getClass()) {
            return false;
        }
        Rating other = (Rating) obj;
        return this.average == other.average && this.count == other.count;
    }

    /**
     * Return a hash code for this rating.
     */
    public int hashCode() {
        return Objects.hash(this.average, this.count);
    }
}
